# SonarCloud configuration
sonar.projectKey=sebastianfuentesavalos_bank-domain-lab-pds
sonar.organization=sebastianfuentesavalos

# Project info
sonar.projectName=Bank Domain - Lab PDS
sonar.projectVersion=1.0

# Source code
sonar.sources=Bank/Bank.Domain
sonar.tests=Bank/Bank.Domain.Tests

# Language
sonar.language=cs

# Coverage
sonar.cs.vstest.reportsPaths=**/TestResults.xml
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/*.Tests.cs,**/bin/**,**/obj/**

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**